version: '3'
services:
  frpc:
    image: snowdreamtech/frps:latest
    container_name: frpclient
    restart: always
    expose:
      - 5000
    volumes:
      - ./config:/config
      - ./log:/log
    extra_hosts:
#     To visit host's port in a container,
#     you should fill in the correct IP of your docker host.
      - "dockerhost:192.168.0.64"
#   ports:
#     - "127.0.0.1:7400:7400" # admin_port
